### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by vmarkovtsev** [sqle/gitquery#122]
`go version` - `go version go1.8.1 linux/amd64`

`go get github.com/sqle/gitquery/cmd/gitquery`

```
src/github.com/sqle/gitquery/cmd/gitquery/query_base.go:9:2: use of internal package not allowed
```

This kinda prevented us from showing the tool on MSR tool session.

**Comment by ajnavarro** [comment]
Hi @vmarkovtsev , the go-git.v4 interface has been changed. I created a new PR (https://github.com/sqle/gitquery/pull/124) that fix the error.

Also, the correct way to obtain the package is `go get -u gopkg.in/sqle/gitquery.v0`.

**Comment by vmarkovtsev** [comment]
Thank you! Successfully built.
