### ISSUE TITLE
Experiencing trouble in installation

### ISSUE THREAD

**Issue by dongjinleekr** [sqle/gitquery#123]
Hello. I am trying to use this tool but experiencing some trouble. When I input `go get github.com/sqle/gitquery` in my command line, the installation fails with following messages:

```
# github.com/sqle/gitquery
opt/go/src/github.com/sqle/gitquery/commits.go:52: cannot use cIter (type object.CommitIter) as type *object.CommitIter in field value:
    *object.CommitIter is pointer to interface, not interface
opt/go/src/github.com/sqle/gitquery/commits.go:65: i.i.Next undefined (type *object.CommitIter is pointer to interface, not interface)
opt/go/src/github.com/sqle/gitquery/commits.go:73: i.i.Close undefined (type *object.CommitIter is pointer to interface, not interface)
```

Since I am a total newbie in golang, I don't even know whether it is a bug or not. However, is this a bug? I am running go with go1.8.3 linux/amd64 in Ubuntu 16.04.

Thanks for reading. Looking forward to your response.

**Comment by stuartskelton** [comment]
I get the same on go version go1.8.3 darwin/amd64

**Comment by ajnavarro** [comment]
Hi @dongjinleekr , the go-git.v4 interface has been changed. I created a new PR (https://github.com/sqle/gitquery/pull/124) that fix the error.
